name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: install crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: compile
        run: |
          crystal build src/sudont.cr --release -O3 -o sudont-glibc

      - name: put on release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-sudont
          name: latest-sudont
          files: sudont-glibc

  build-musl:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          apk add --no-cache curl bash git

      - name: install crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: compile
        run: |
          crystal build src/sudont.cr --release -O3 -o sudont-musl

      - name: put on release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-sudont
          name: latest-sudont
          files: sudont-musl