name: build

on:
 push:
  paths:
     - "sudont.cr"
 workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: install crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: compile
        run: |
          crystal build src/sudont.cr \
            --release \
            -O3 \
            --static \
            -o sudont-glibc

      - name: upload glibc
        uses: actions/upload-artifact@v4
        with:
          name: sudont-glibc
          path: sudont-glibc

  build-musl:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest-alpine

    steps:
      - name: download code
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          apk add --no-cache \
            gc-static \
            gcc \
            musl-dev \
            binutils

      - name: check crystal
        run: |
          crystal --version
          shards --version

      - name: compile
        run: |
          crystal build src/sudont.cr \
            --release \
            -O3 \
            --static \
            -o sudont-musl

      - name: upload musl
        uses: actions/upload-artifact@v4
        with:
          name: sudont-musl
          path: sudont-musl

  put-releases:
    needs:
      - build
      - build-musl

    runs-on: ubuntu-latest

    steps:
      - name: download glibc
        uses: actions/download-artifact@v4
        with:
          name: sudont-glibc

      - name: download musl
        uses: actions/download-artifact@v4
        with:
          name: sudont-musl

      - name: make release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-sudont
          name: latest-sudont
          files: |
            sudont-glibc
            sudont-musl
          overwrite_files: true